version: '3.8'

services:
  redis: # Serviço Redis
    container_name: redis-cache
    image: redis:latest
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis_data:
    driver: local
